// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxZg7ZDjloo9LpUK9aqxJR0uASs2Dp6as',
    appId: '1:385581118113:android:f992bcd22a2e306d43f6e0',
    messagingSenderId: '385581118113',
    projectId: 'tomorrow-e4036',
    storageBucket: 'tomorrow-e4036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRGtldQhqByftloEVtkxEJiaCc0tsVY3w',
    appId: '1:385581118113:ios:6bafb9f980f2187b43f6e0',
    messagingSenderId: '385581118113',
    projectId: 'tomorrow-e4036',
    storageBucket: 'tomorrow-e4036.appspot.com',
    androidClientId: '385581118113-otfgf38o6rfnd1jmov2q4p300748fqbr.apps.googleusercontent.com',
    iosClientId: '385581118113-ok9iugs2pmfjlv1etqb813mrr072hu58.apps.googleusercontent.com',
    iosBundleId: 'com.gitinofficial.toMorrowFront',
  );
}
